# Generated by Django 5.0.2 on 2024-03-01 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('min_students', models.IntegerField(verbose_name='Минимальное количество учащихся')),
                ('max_students', models.IntegerField(verbose_name='Максимальное количество учащихся')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время запуска курса')),
                ('price', models.IntegerField(verbose_name='Возраст')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='platform_users.author')),
            ],
        ),
    ]
