# Generated by Django 5.0.2 on 2024-03-01 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_users', '0001_initial'),
        ('product', '0002_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='product.course')),
                ('student', models.ManyToManyField(blank=True, to='platform_users.student')),
            ],
        ),
    ]
