# Generated by Django 5.0.2 on 2024-03-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_users', '0002_alter_author_name'),
        ('product', '0003_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость курса'),
        ),
        migrations.CreateModel(
            name='Group_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='product.group')),
                ('student', models.ManyToManyField(blank=True, to='platform_users.student')),
            ],
        ),
    ]
