# Generated by Django 5.0.2 on 2024-03-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_users', '0002_alter_author_name'),
        ('product', '0004_remove_group_student_alter_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(blank=True, to='platform_users.student'),
        ),
        migrations.DeleteModel(
            name='Group_students',
        ),
    ]
