# Generated by Django 5.0.2 on 2024-03-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_users', '0002_alter_author_name'),
        ('product', '0005_group_student_delete_group_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='platform_users.student'),
        ),
    ]
