# Generated by Django 5.0.2 on 2024-03-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='Somebody', max_length=255, verbose_name='Имя'),
        ),
    ]
